### PR TITLE
Change spec title

### PR DESCRIPTION
**Pull request by OR13**
To: JSON Web Signatures for Data Integrity Proofs

Addresses #31

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jws-2020/pull/32.html" title="Last updated on Jan 16, 2023, 2:51 PM UTC (78b17c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jws-2020/32/98a032c...78b17c9.html" title="Last updated on Jan 16, 2023, 2:51 PM UTC (78b17c9)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
This would need a change in the short name of the document as well, which is a painful (but doable) thing to do with the W3C publication system. Just saying...

**Comment by OR13** [comment]
@iherman why would we be required to change the short name?

**Comment by iherman** [comment]
> @iherman why would we be required to change the short name?

Well... there is no _obligation_ of course. But it looks funny to have short name (`jws-2020`) for a specification whose title does not have any date nor version number.

**Comment by OR13** [comment]
@iherman lets focus on fixing the name of the working group first: https://lists.w3.org/Archives/Public/

Screen Shot 2023-01-17 at 11 44 00 AM

**Review by brentzundel — APPROVED** [review]

**Review by selfissued — APPROVED** [review]
We should do this - especially since it comes from liaison feedback from the IETF.

**Comment by brentzundel** [comment]
Multiple approvals, 2 weeks of review time. Merging.

**Pull request merged**
