### PR TITLE
Create a First Public Working Draft for Json Web Signature Data Integrity. 

### PR DESCRIPTION
**Pull request by OR13**
Similar to https://github.com/w3c/vc-data-integrity/pull/67

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jws-2020/pull/26.html" title="Last updated on Nov 22, 2022, 2:20 PM UTC (e81e194)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-jws-2020/26/d7318cc...e81e194.html" title="Last updated on Nov 22, 2022, 2:20 PM UTC (e81e194)">Diff</a>

### CODE REVIEW

**Comment by OR13** [comment]
draft proposal:

PROPOSAL: The WG will publish as a FPWD the document at https://w3c.github.io/vc-jws-2020/, on 2022-11-10 under the shortname vc-jws-2020, and will use echidna to automatically update the working draft when PRs are merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-10-26-vcwg#section1-4) on 2022-10-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.4. Create a First Public Working Draft for Json Web Signature Data Integrity.  (pr vc-jws-2020#26)

_See github pull request [vc-jws-2020#26](https://github.com/w3c/vc-jws-2020/pull/26)._




**Orie Steele:** I'm going to skip over that one, it's a long discussion..  
… PR #26 is the FPWD for JsonWebSignature2020. It's the same kind of PR that Manu just commented on..  
… And that's it for JsonWebSignature2020, please look at those PRs..  
… On VC-JWT, there is one PR remaining..  

</details>

**Comment by iherman** [comment]
> draft proposal:
>
> PROPOSAL: The WG will publish as a FPWD the document at https://w3c.github.io/vc-jws-2020/, on 2022-11-10 under the shortname vc-jws-2020, and will use echidna to automatically update the working draft when PRs are merged.

For the records, see https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-10-26-vcwg#resolution2 on the approval.

**Review by iherman — CHANGES_REQUESTED** [review]
- I am not sure the publication rules will accept the CCG report as "latest published version". That field usually refers to the versions officially published by W3C on its core `/TR` area, and that is not the case of a CG report. I would suggest taking that out.
- The RCH WG is in the process of publishing a FPWD of the RDF Normalization spec. *If* they are quicker than us, then we should refer to that document and not to the CG Draft.

    Even if the CG draft is used, the reference seems to be outdated; it should be https://w3c-ccg.github.io/rdf-dataset-canonicalization/spec/index.html (cc @philarcher @peacekeeper)
- @philarcher @peacekeeper @dlongley what is the status of the LD-Proofs document v.a.v. the RCH WG? Do we have a better reference than https://w3c-ccg.github.io/ld-proofs?
- (Also related to the previous points) CCG documents cannot be used as normative references, only informative ones. If we are on a waiting cycle with RCH, we have to mark them as such.
- The proper reference to RDF 1.1 Quads is https://www.w3.org/TR/n-quads/

**Comment by iherman** [comment]
> * I am not sure the publication rules will accept the CCG report as "latest published version". That field usually refers to the versions officially published by W3C on its core `/TR` area, and that is not the case of a CG report. I would suggest taking that out.

Actually, I realized I was wrong in my comment. The 'latest published version' _MUST_ say `https://www.w3.org/TR/vc-jws-2020/` (actually, respec should produce that automatically if the 'short name' is properly set in the preamble.)

**Comment by OR13** [comment]
@iherman can we please rephrase your change request with specific instructions for me to fix?

**Comment by OR13** [comment]
Do I just copy the spec changes here: https://github.com/w3c/vc-data-integrity/pull/67/files ?

**Comment by iherman** [comment]
> @iherman can we please rephrase your change request with specific instructions for me to fix?

The 'latest published version' must be 'https://www.w3.org/TR/vc-jws-2020/. 

I believe (but you have to check) that simply leaving out the

  latestVersion: "https://www.w3.org/community/reports/credentials/CG-FINAL-lds-jws2020-20220721/",

line in the preamble will force respec to do the right thing.

**Review by mprorock — APPROVED** [review]

**Comment by mprorock** [comment]
approved - caveat update per ivan's comment

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-11-02-vcwg#section1-6) on 2022-11-02

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.6. Create a First Public Working Draft for Json Web Signature Data Integrity.  (pr vc-jws-2020#26)

_See github pull request [vc-jws-2020#26](https://github.com/w3c/vc-jws-2020/pull/26)._




**Orie Steele:** let's move on to VC-JWS-2020.  
… other PR that has been open for quite some time, some extra steps to do to be ready for FPWD.  

**Ivan Herman:** i need advice on that, from orie and chairs.  
… should i wait for public wg draft for data integrity?.  
… (I could start process for data integrity today or tomorrow morning).  
… question to chairs and editors.  

**Orie Steele:** i would not wait and would proceed independently.  

**Ivan Herman:** ok, agreed. understood.  

> *Michael Prorock:* +1 proceed along, then update separately.

</details>

**Comment by OR13** [comment]
@iherman can you please re-review.

**Review by iherman — CHANGES_REQUESTED** [review]
Sorry, there are things that I did not spot before, my bad. I spotted the same in the other FPWD and I thought this would was also done here

1. The status section says "This is an experimental specification and is undergoing regular revisions. It is not fit for production deployment". This sentence should go; and experimental specification cannot be rec-track... The standard blurb generated by respec should suffice.
2. A Community group draft cannot be listed as a normative spec. (LD-Proof and RDF normalization). Those should be informal references. B.t.w. the references are also probably wrong: the rdf dataset normalization is not a JSON-LD CG document, the LD Data Proofs is not a Web Payment CG document. I am not sure what the correct references should be, @msporny or @dlongley probably know.
3. For the publication date of the final document: the 10th is impossible. The FPWD formal request should go in for approval by the Director, and these decisions fall on Fridays. Publications (non-echidna ones, that is) happen on Tuesdays or Thursdays. Earliest possible date is next week Tuesday, possibly next week Thursday...

Again, apologies not to have caught these before...

**Comment by TallTed** [comment]
Should probably delete [`CGFR/.DS_Store`](https://github.com/w3c/vc-jws-2020/pull/26/files/a53cc3f3bd66be3ed5973b8a55e3050d0b9131b1..26cb38fa284321cfc70678e2903993f2da3a1d17#diff-a18916a2ea15d77e5ea7130558d8c8d5129ec8c4c98703ef81377e40d350ffec)

**Comment by OR13** [comment]
@iherman I have applied the feedback, please review again.

I will add references to the RCH and VC-DATA-INTEGRITY at a future date.

**Review by iherman — APPROVED** [review]
Thanks @OR13 

two remarks.

1. For the publication date, _if_ we wanted to publish it next week, the approval of the director should be taken on this coming Friday. For that to happen, I should be in position to issue an official publication request today (Wed) evening or tomorrow morning. I am happy to do that, but you will have to ping me to be sure. However:
    - You will have to check the final format of the document with the pubrules checker asap, mainly if we want to publish it on Tuesday 15. If we opt for Thursday 17, then we can be more relaxed.
    - I do not know whether Veterans' day is a public holiday in MA or not, ie, whether the Director will operate on that day. If there is a doubt, we may have to postpone everything for a week. (I will ask them)
2. I believe the pubrules checker will accept it as is, but the usual placement for the conformance section is at the beginning of a document, and not towards the end as it is now. I believe that, eventually, it would be better to move it, but that can be done in a later draft.

Again, my apologies not to have spotted those problems earlier.

**Comment by OR13** [comment]
@iherman given the time lapse and IETF and IIW, can you suggest an appropriate date in the future for me to make changes?

**Comment by iherman** [comment]
The coming week is Thanksgiving week in the USA, which means the director's decision is not possible (these are usually taken on Fridays). I'm also out for a long week-end (nothing to do with Thanksgiving). Let us plan to issue the transition request on the week of the 28th of November, with a decision expected on the 2nd of December. The available publication dates might then be the 6th or 8th of December.

If you can prepare the final formatted document that pass the pubrules' checker for the 29 or the 30, I can install it and get a webmaster's preliminary check on that week (alongside issuing a formal publication request), and the publication can happen on the 6th. Caveat, I am not working on Mondays, ie, if you hit some formatting error with the webmaster by the Monday 5th, I am not necessarily around. If you want to take it on the safe side, pick the 8th as a publ date.

**Comment by OR13** [comment]
@iherman I have set the date in https://github.com/w3c/vc-jws-2020/pull/26/commits/9abeae98f9e82fb5c7c816f762f25e9b46593bc2

Would you be willing to merge this if it meets with your approval?

Otherwise I am happy to merge after your confirmation

**Comment by iherman** [comment]
@OR13 I have installed the document on TR, ie, there is now a copy on its final resting place:

https://www.w3.org/TR/2022/WD-vc-jws-2020-20221208/

and I will issue an official request. The document passes the pubrules' checker (thank you) but there is one error in the link checker, namely:

> error Line: 587 https://w3c-ccg.github.io/data-integrity-spec/
>
> Broken fragments:
> https://w3c-ccg.github.io/data-integrity-spec/#signatures (line 587)

Actually, I get a 404 on https://w3c-ccg.github.io/data-integrity-spec/. I presume the link should be to the official document by now.

Please settle this last bit asap, and then you should merge the PR. Ping me explicitly when it is done, so that I could refresh the document on the TR page.

(P.S. In general, I prefer to keep to the rules whereby PR-s are merged by code owners/editors. I prefer not to use my admin powers, so to say…)

**Comment by iherman** [comment]
@OR13 I have actually spotted one more minor issue in the abstract. You have changed the "Linked Data Proof" term to Data Integrity everywhere else in the document, but you forgot to do it in the abstract... Could you change that, too?

**Comment by iherman** [comment]
FYI: the official transition request has been issued in https://github.com/w3c/transitions/issues/475

**Comment by OR13** [comment]
@iherman I have merged the PR with your feedback.

**Pull request merged**
